ARG BUILD_PYTHON_VERSION=3.11
ARG BUILD_NODE_VERSION=18
ARG RUN_NODE_VERSION=18

###################################################################################################
FROM nikolaik/python-nodejs:python${BUILD_PYTHON_VERSION}-nodejs${BUILD_NODE_VERSION}-alpine AS buildstage

RUN apk add --update-cache \
    build-base \
  && rm -rf /var/cache/apk/*

WORKDIR /usr/src/app/
COPY . .

RUN npm ci
RUN npm run build
RUN npm pack

###################################################################################################
FROM node:${RUN_NODE_VERSION}-alpine AS runstage

RUN apk add --update-cache \
    valgrind \
  && rm -rf /var/cache/apk/*

WORKDIR /usr/src/app/
COPY fixtures/integrating-app .
COPY fixtures/data .
COPY valgrind.supp .

COPY --chown=node:node --from=buildstage /usr/src/app/openssl-napi-*.tgz .

RUN npm i openssl-napi-*.tgz

CMD ["sleep", "infinity"]